name: Test
on:
  workflow_dispatch:
    inputs:
      firstName:
        description: 'First Name'
        required: true
      lastName:
        description: 'Last Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        shell: python
        run: |
          print(f"${{github.event.inputs.firstName}}, { 1 + 1 }")
          print(f"${{github.event.inputs.lastName}}, { 1 + 1 }")
