name: Test
on:
  push

jobs:
  safe_space:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo 42 > its_a_secret_to_everybody.txt
          echo sowise > this_is_my_intellectual_property.txt
          echo snow > kind_of_public.txt
      - uses: actions/upload-artifact@v2
        with:
          name: public-artifact
          path: |
            **/*public*

  uses_third_party_actions:
    needs: safe_space
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@782e5ae9ea8551dd997e5c4dd22499cb62797251
        with:
          name: public-artifact
      - run: |
          ls
          cat kind_of_public.txt
