name: Test
on:
  workflow_dispatch:
    inputs:
      firstName:
        description: 'First Name'
        required: true
      lastName:
        description: 'Last Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          commandThatDoesNotExist
          echo ${{github.event.inputs.firstName}}
          echo ${{github.event.inputs.lastName}}
