name: Test
on:
  workflow_dispatch:
    inputs:
      firstName:
        description: 'First Name'
        required: true
      lastName:
        description: 'Last Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        shell: python
        run: |
          import sys
          print(sys.version)
          print("${{github.event.inputs.firstName}}")
          print("${{github.event.inputs.lastName}}")
